services:
  asr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asr-service
    env_file:
      - .env
    ports:
      - "${ASR_SERVICE_PORT:-8032}:${ASR_SERVICE_PORT:-8032}"
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
